#!/usr/bin/env python3
"""Generate payment.v1.schema.json = receipt.v1 core + `payment` object.

receipt.v1.schema.json is a byte-identical copy of the source protocol and carries
`unevaluatedProperties: false` at its root. In JSON Schema 2020-12 that keyword only sees
properties evaluated *inside that schema object*, so an `allOf: [{$ref: base}, {payment}]`
profile is rejected by the base itself. This script therefore embeds the base's core keywords
(everything except `$schema`, `$id`, `unevaluatedProperties`) under `$defs.receipt_core` and
closes the profile with its own `unevaluatedProperties: false`. Re-run after the base changes.
"""
import json, pathlib
here = pathlib.Path(__file__).parent
base = json.loads((here / "receipt.v1.schema.json").read_text(encoding="utf-8"))
core = {k: v for k, v in base.items() if k not in ("$schema", "$id", "unevaluatedProperties")}
leg = {
    "type": "object",
    "properties": {
        "tinybars": {"type": "integer", "minimum": 1},
        "transaction_id": {"type": "string", "pattern": r"^0\.0\.[0-9]+@[0-9]+\.[0-9]+$",
                           "description": "Hedera transaction id as returned by the facilitator, e.g. 0.0.7162784@1788539653.433840739"},
        "consensus_timestamp": {"type": "string", "pattern": r"^[0-9]+\.[0-9]+$"},
        "anchor": {"type": "object", "additionalProperties": False, "required": ["topic"],
                   "properties": {"topic": {"type": "string", "pattern": r"^0\.0\.[0-9]+$"},
                                  "seq": {"type": ["integer", "null"]},
                                  "consensus_ts": {"type": ["string", "null"]}}},
    },
    "required": ["tinybars", "transaction_id"],
    "additionalProperties": False,
}
profile = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/retailbox-automation/x402-work-receipts/docs/schemas/payment.v1.schema.json",
    "title": "receipt.v1 + payment.v1 (x402-work-receipts profile)",
    "$comment": ("GENERATED by build_payment_profile.py from receipt.v1.schema.json (source: RetailBox A2A Bridge, "
                 "spec 2026-09-04 §3.2). The base forbids money fields by design; this profile adds `payment` and is "
                 "the only schema in this repo that accepts it. Amounts are in tinybars (1 HBAR = 100 000 000)."),
    "allOf": [
        {"$ref": "#/$defs/receipt_core"},
        {"type": "object", "required": ["payment"], "properties": {"payment": {
            "type": "object",
            "description": "x402 payments this receipt accounts for: `intake` settled on acceptance, `balance` on delivery.",
            "properties": {
                "network": {"type": "string", "enum": ["hedera:testnet", "hedera:mainnet"]},
                "asset": {"type": "string", "pattern": r"^0\.0\.[0-9]+$", "description": "`0.0.0` = HBAR, otherwise an HTS token id"},
                "facilitator": {"type": "string", "format": "uri"},
                "payer": {"type": "string", "pattern": r"^0\.0\.[0-9]+$"},
                "payee": {"type": "string", "pattern": r"^0\.0\.[0-9]+$"},
                "intake": {"$ref": "#/$defs/leg"},
                "balance": {"$ref": "#/$defs/leg"},
            },
            "required": ["network", "asset", "facilitator", "payer", "payee", "intake"],
            "additionalProperties": False,
        }}},
    ],
    "unevaluatedProperties": False,
    "$defs": {"receipt_core": core, "leg": leg},
}
(here / "payment.v1.schema.json").write_text(json.dumps(profile, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print("payment.v1.schema.json regenerated from receipt.v1 core")
