/**
 * Schema validation against the canonical schemas in `docs/schemas`.
 *
 * The schema files are read from the repository at runtime and never copied
 * or edited here: `mandate.v1` and `receipt.v1` are byte-identical copies of
 * the source protocol, and `payment.v1` is generated by
 * `docs/schemas/build_payment_profile.py`. Keeping them as the single source
 * means a document that passes here also passes for the counterparty.
 */
import { readFileSync } from "node:fs";
import Ajv2020Import from "ajv/dist/2020.js";
import type { ErrorObject, ValidateFunction } from "ajv";
import addFormatsImport from "ajv-formats";
import type { EnvelopeSchema, Mandate, PaymentReceipt, Receipt } from "./types.js";

// ajv and ajv-formats are CommonJS: Node hands back `module.exports` while
// bundlers unwrap `.default`, so accept either shape.
const Ajv2020 = ((Ajv2020Import as { default?: typeof Ajv2020Import }).default ??
  Ajv2020Import) as typeof Ajv2020Import;
const addFormats = ((addFormatsImport as { default?: typeof addFormatsImport }).default ??
  addFormatsImport) as typeof addFormatsImport;

/** A document that does not match its schema. */
export class SchemaError extends Error {
  /** Schema the document was checked against, named as on the envelope tag. */
  readonly schema: EnvelopeSchema;
  /** The ajv errors, in ajv's own shape, for callers that want details. */
  readonly errors: ErrorObject[];

  /**
   * @param schema - Schema the document failed
   * @param errors - Errors reported by ajv
   */
  constructor(schema: EnvelopeSchema, errors: ErrorObject[]) {
    super(`${schema}: ${describe(errors)}`);
    this.name = "SchemaError";
    this.schema = schema;
    this.errors = errors;
  }
}

// The base schemas come from another repository and are not edited here; ajv's
// strict mode rejects two of their constructs (`strictRequired` inside an
// if/then, an untyped `unevaluatedProperties`), so it stays off. Validation
// behaviour is unaffected.
const ajv = new Ajv2020({ strict: false, allErrors: true });
addFormats(ajv);

const validators = {
  "mandate.v1": compile("mandate.v1.schema.json"),
  "receipt.v1": compile("receipt.v1.schema.json"),
  "receipt.v1+payment.v1": compile("payment.v1.schema.json"),
} as const;

/**
 * Checks a document against `mandate.v1`.
 *
 * @param data - Untrusted document
 * @throws SchemaError when the document does not match
 */
export function validateMandate(data: unknown): asserts data is Mandate {
  check("mandate.v1", data);
}

/**
 * Checks a document against the base `receipt.v1`, which carries no money
 * fields: a receipt with a `payment` object is rejected here and belongs to
 * `validatePaymentReceipt`.
 *
 * @param data - Untrusted document
 * @throws SchemaError when the document does not match
 */
export function validateReceipt(data: unknown): asserts data is Receipt {
  check("receipt.v1", data);
}

/**
 * Checks a document against this repository's `payment.v1` profile:
 * `receipt.v1` plus the required `payment` object.
 *
 * @param data - Untrusted document
 * @throws SchemaError when the document does not match
 */
export function validatePaymentReceipt(data: unknown): asserts data is PaymentReceipt {
  check("receipt.v1+payment.v1", data);
}

/**
 * Runs one compiled validator and raises on failure.
 *
 * @param schema - Which schema to use
 * @param data - Untrusted document
 * @throws SchemaError when the document does not match
 */
function check(schema: EnvelopeSchema, data: unknown): void {
  const validate = validators[schema];
  if (!validate(data)) {
    throw new SchemaError(schema, validate.errors ?? []);
  }
}

/**
 * Compiles one schema file from `docs/schemas`.
 *
 * @param file - File name inside `docs/schemas`
 * @returns The compiled validator
 */
function compile(file: string): ValidateFunction {
  const url = new URL(`../docs/schemas/${file}`, import.meta.url);
  return ajv.compile(JSON.parse(readFileSync(url, "utf8")) as object);
}

/**
 * Renders ajv errors as one line, keeping the instance path so the caller can
 * see which field failed.
 *
 * @param errors - Errors reported by ajv
 * @returns A human-readable summary
 */
function describe(errors: ErrorObject[]): string {
  if (errors.length === 0) return "invalid document";
  return errors.map(describeOne).join("; ");
}

/**
 * Renders one ajv error as `<json pointer> <what is wrong>`.
 *
 * @param error - One error reported by ajv
 * @returns The rendered error
 */
function describeOne(error: ErrorObject): string {
  const missing = error.params?.["missingProperty"];
  if (typeof missing === "string") return `${error.instancePath}/${missing} is required`;
  const unevaluated = error.params?.["unevaluatedProperty"] ?? error.params?.["additionalProperty"];
  if (typeof unevaluated === "string") return `${error.instancePath}/${unevaluated} is not allowed here`;
  return `${error.instancePath || "/"} ${error.message ?? "is invalid"}`;
}
